### ISSUE TITLE
After update from 0.95.4 to 0.96+ : 'IXLWorkbook' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by tossnet** [ClosedXML/ClosedXML.Report#289]
Simply by upgrading the package from version 0.95.4 to version 0.96 or 0.97.
I get this error: 
`Error	CS0012	The type 'IXLWorkbook' is defined in an assembly that is not referenced. You must add a reference to assembly 'ClosedXML, Version=0.95.0.0, Culture=neutral, PublicKeyToken=null'.`

By doing a regression in 0.95.4, the problem disappears

`  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.97.0" />
    <PackageReference Include="ClosedXML.Report" Version="0.2.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.10" PrivateAssets="all" />
  </ItemGroup>`

![image](https://user-images.githubusercontent.com/3845786/197333481-f1aee5e7-ec2f-470f-8266-2dd62bbcdfa5.png)

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Version of ClosedXML**
 0.96

## Reproducibility

With this repo, you just have to upgrade CloseXML to version 0.96 or 0.97 : https://github.com/tossnet/Blazor-Excel-export

**Comment by jahav** [comment]
It's an strange issue, caused probably because0.96 has switched from net4x to net standard.

The net4x uses assembly redirects to solve these kinds of problems, while net core has more "relaxed" assembly resolution. I am not sure what exactly is the problem here 

I moved it because it should be resolved by updating the ClosedXml.Report

**Comment by sopelt** [comment]
This seems to be tracked in https://github.com/ClosedXML/ClosedXML.Report/issues/194

**Comment by jahav** [comment]
Duplicate of #194

**Comment by fingers10** [comment]
@jahav @Pankraty @b0bi79 I still see this issue in `.NET 9 blazor wasm` app. I'm trying to build a in-browser demo for closed xml report - https://ilovedotnet.org/blogs/generate-excel-report-using-closed-xml-in-dotnet/

Nuget Added:
```csproj
<PackageReference Include="ClosedXML" Version="0.104.2" />
<PackageReference Include="ClosedXML.Report" Version="0.2.10" />
```

```cs
var file = await HttpClient.GetStreamAsync("./files/ILoveDotNetContentTemplate.xlsx");
        
var template = new XLTemplate(file);

template.AddVariable(complexData);
template.Generate();
template.Workbook.Worksheets
    .Worksheet(template.Workbook.Worksheets.First().Name)
    .ColumnsUsed()
    .AdjustToContents();

using var stream = new MemoryStream();
template.SaveAs(stream);
```

Here is the error message

> The type 'IXLWorkbook' is defined in an assembly that is not referenced. You must add a reference to assembly 'ClosedXML, Version=0.102.2.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b'.

When I try to install `ClosedXML 0.102.2.0`, WASM app breaks... Any hints on where to go from here?
